### ISSUE TITLE
Atlas lcmtypes error when building w/o atlas_drivers external

### ISSUE THREAD

**Issue by Rahtron3030** [openhumanoids/oh-distro#116]
I am trying to build OH without access to the atlas_drivers external (but have access to SNOPT and built gurobi on its own) and am getting the following errors:

> [ 14%] Building CXX object src/CMakeFiles/AtlasFallDetector.dir/AtlasFallDetector.cpp.o
> In file included from /home/rc/oh-distro/software/control/src/AtlasFallDetector.cpp:1:0:
> /home/rc/oh-distro/software/control/src/AtlasFallDetector.hpp:12:39: fatal error: lcmtypes/atlas/status_t.hpp: No such file or directory
>  #include "lcmtypes/atlas/status_t.hpp"
>                                        ^
> compilation terminated.
> make[4]: *** [src/CMakeFiles/AtlasFallDetector.dir/AtlasFallDetector.cpp.o] Error 1
> make[3]: *** [src/CMakeFiles/AtlasFallDetector.dir/all] Error 2
> make[2]: *** [all] Error 2
> make[1]: *** [all] Error 2
> make: *** [all] Error 2

I tried cd'ing into drc_lcmtypes, doing a make clean, then make again in /software. That didn't work.

**Comment by patmarion** [comment]
I've opened pull request #117 which I think fixes the problem.  You could test it yourself by making the same change locally to atlas-collection/CMakeLists.txt:

https://github.com/openhumanoids/oh-distro/pull/117/files

**Comment by patmarion** [comment]
@Rahtron3030 this should be fixed now after you do a git pull.  Thanks for reporting it!
