### ISSUE TITLE
Broken tests after switching to Valkyrie default

### ISSUE THREAD

**Issue by patmarion** [openhumanoids/oh-distro#22]
Two tests have been broken after switching to Valkyrie as the default robot:

testTelopPanel.py
http://kobol.csail.mit.edu/cd/testDetails.php?test=3491786&build=19960

testContinuousWalking.py
http://kobol.csail.mit.edu/cd/testDetails.php?test=3491780&build=19960

Either we should add args to these tests so that they use Atlas v5, or we should update the tests to correctly use the Valkyrie model.  Even better, adapt the tests so they pass with Atlas or Valkyrie, then run the tests in both modes!

**Comment by mauricefallon** [comment]
It would be great to get back to running that for real!

Certainly some of the tests need to run on Atlas in future
