### ISSUE TITLE
Encapsulate Atlas specific API and types

### ISSUE THREAD

**Issue by mauricefallon** [openhumanoids/oh-distro#30]
I intend to gather up all Atlas specific code into a single place such that:
- software builds without drc_atlas lcm types. There are 30 of these currently.
- software builds without BDI proprietary library
- this will also simplify the dependency tree
- move us a couple of steps closer to full open source (i.e. checkout and build)

The steps:
- [x] Fish out the 30 LCM types into a pod
- [x] Move all dependent code into a single place: state-sync, bdi-footstep-translator.
- [x] Fix some minor dependencies on these types e.g. signal scope and the fall detector
- [ ] Gather the dependent code and types with the driver (and disable by default)

Then during Valkyrie development, we will avoid the intermingling of our software and the manufacturer's API and proprietary files.

**Comment by iamwolf** [comment]
I've checked off most of those today (apart from LCM types) and am just running a few last tests before making a pull request: https://github.com/oh-dev/oh-distro/tree/wolfgang-make-public-compilable

**Comment by iamwolf** [comment]
[If you're reading from email, please disregard my earlier comment - it is updated online on GitHub; apologies for the extra email noise]

**Comment by mauricefallon** [comment]
The list of issues from that branch is useful. Judging from it, only a small number of issues needs be resolved.

Lets fix the Atlas dependency first.

**Comment by mauricefallon** [comment]
This wasn't fully complete as when the Atlas was used the control directory was dependent on atlas_collections, so had to be reverted. will explore again in future
