### ISSUE TITLE
Redesign drc_robot_command_t

### ISSUE THREAD

**Issue by oh-dev** [openhumanoids/oh-distro#4]
As discussed with @gizatt , we will re work this to be a set of vectors of properties
rather than a vector of sets of properties - as we previously used to do.
(This fits with current tools and ROS conventions)

I'll work on this.

**Comment by mauricefallon** [comment]
@gizatt : any problem with me moving to use the old drc_atlas_command_t type for this? The contents are the same

(It can also be renamed to be drc_robot_command_t and still be backwardly compatible for Atlas)

**Comment by gizatt** [comment]
Nope, that was the original intention until Robin and I went down this alternate route. Just renaming that type would work great. I can help move over the translator / relevant scripts if you want, but it should be an easy change

**Comment by mauricefallon** [comment]
Ok, go for it.

**Comment by gizatt** [comment]
Though -- the atlas_command_t contains some VRC-holdover fields that really ought not to be kept around if we can avoid it. Can I cut those out? (How strict do you want this compatibility to be?)

**Comment by mauricefallon** [comment]
Since we get to decide the interface this time around, it could be anything.

I'd suggest using drc_atlas_command_t as is for now and then moving to a new type (e.g. drc_robot_command_t) when you have a good idea about what you need.
It's useful to playback old logs and to be able to decode the data (obviously). But making a new type is fine.

**Comment by gizatt** [comment]
Switched over the LCM2ROSControl plugin to use atlas_command_t on a branch https://github.com/gizatt/oh-distro/tree/gizatt_switch_to_temp_cmd_msg_type. Hopefully I interpreted  your recommendation correctly: we won't stick with atlas_command_t to command the driver, but while we're working out what robot_command_t should really contain, we can use the old command that we can guarantee won't change, to keep our logs compatible.

**Comment by gizatt** [comment]
Also are you going to make these changes (or should I -- maybe bundled with the message-swapping PR I'm going to make soon?)

**Comment by mauricefallon** [comment]
Yes, I'll leave it to you to make the changes then Pat or I can test it tomorrow on the robot.

**Comment by mauricefallon** [comment]
resolved
