### ISSUE TITLE
Occ-map compilation error (using system-installed OpenCV)

### ISSUE THREAD

**Issue by Rahtron3030** [openhumanoids/oh-distro#80]
During compilation, cloning OpenCV would freeze and quit after 3 attempts. Instead I used the system-installed instructions for OpenCV. When compiling, I got the following errors:

"Linking CXX executable ../../bin/occ-map-img-to-pixmap
/usr/bin/ld: warning: libdc1394.so.22, needed by /usr/local/lib/libopencv_highgui.so, not found (try using -rpath or -rpath-link)
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_video_set_transmission'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_feature_set_value'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_video_set_iso_speed'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_feature_set_absolute_control'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_feature_set_power'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_feature_get_value'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_get_color_coding_from_video_mode'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_camera_free'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_convert_frames'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_camera_free_list'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_capture_is_frame_corrupt'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_video_set_operation_mode'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_video_get_supported_modes'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_debayer_frames'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_set_control_registers'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_free'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_video_get_mode'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_camera_new'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_video_get_supported_framerates'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_feature_get_all'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_get_image_size_from_video_mode'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_feature_whitebalance_set_value'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_video_set_mode'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_capture_dequeue'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_deinterlace_stereo'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_capture_enqueue'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_capture_stop'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_capture_setup'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_feature_set_mode'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_get_control_registers'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_capture_get_fileno'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_video_set_framerate'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_get_color_coding_bit_size'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_feature_whitebalance_get_value'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_new'
/usr/local/lib/libopencv_highgui.so: undefined reference to `dc1394_camera_enumerate'
collect2: error: ld returned 1 exit status
make[7]: *** [bin/occ-map-img-to-pixmap] Error 1
make[6]: *** [src/map_server/CMakeFiles/occ-map-img-to-pixmap.dir/all] Error 2
make[5]: *** [all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [src/occ-map-stamp/occ-map-build] Error 2
make[2]: *** [CMakeFiles/occ-map.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
"

**Comment by iamwolf** [comment]
Hey Rahul!
You need to install libdc1394-22-dev when using system OpenCV:
``sudo apt-get install libdc1394-22-dev``.

Hope this helps,
Wolfgang
